### ISSUE TITLE
Net promoter score calculation in dashboard view

### ISSUE THREAD

**Issue by gaiarc** [danewatkins/arnolfini-dataviz#1]
Hi Dane, as discussed please could you kindly change the Net Promoter score dials so that it's showing the score rather than the average rating from visitors? This is how the NPS score is calculated:

People who rated the question from 0% to 64% are called detractors
People who rated the question between 65% and 84% are called passives
People who rated the question between 85% and 100% are called promoters

If, for example, there are:
3 detractors (16% of all responses);
6 passives (31% of all responses);
10 promoters (53% of all responses);

then the NPS score is 53 (promoters %), minus 16 (detractors %) = 37 (as very helpfully illustrated in this diagram here https://delighted.com/nps-calculator) 

So ideally in the dial I would want to see the NPS itself (eg. 37), and/or the % of promoters, % detractors and % passives (this really helps me too to understand how the score is doing and why).

If that is tricky I'm happy to consider another ways of displaying the info, so let me know!

Thanks,
Gaia

**Comment by danewatkins** [comment]
Completed
