### ISSUE TITLE
Generating spreadsheet of individual responses data

### ISSUE THREAD

**Issue by gaiarc** [danewatkins/arnolfini-dataviz#3]
Hi Dane

For completeness (though I think you have this on your radar) this is just to remind you that in due course (less urgent than other 2 previous requests) it would be good for me to be able to download the survey data into a kind of spreadsheet form so I can generate my own graphs and analyses. I don' t need this right now though... 

Thanks
Gaia

**Comment by danewatkins** [comment]
Download CSV added Monday 9th October, it has the page number before each response to allow for missing entries.
